spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      pool-name: HikariCP
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081
